-- Chosen NSGA-III + TOPSIS dispatch solution (deep detail for one day):
-- the picked Pareto objectives, the TOPSIS weights that picked it, and the
-- per-device energy breakdown. One row per (day, method); the 96-step power
-- schedule lives in dispatch_schedule (1-to-many via id).
-- Apply with:  psql -d microgrid -f sql/schema/04_dispatch_solution.sql

CREATE TABLE IF NOT EXISTS dispatch_solution (
    id                         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day                        date NOT NULL,
    method                     text NOT NULL,
    forecast_source            text,
    n_pareto                   integer,
    obj_cost_eur               double precision,
    obj_co2_tco2               double precision,
    obj_peak_mw                double precision,
    w_cost                     real,
    w_co2                      real,
    w_peak                     real,
    gas_energy_mwh             double precision,
    gas_fuel_cost_eur          double precision,
    gas_emissions_tco2         double precision,
    gas_load_factor            double precision,
    battery_throughput_mwh     double precision,
    battery_cycles             double precision,
    battery_degradation_eur    double precision,
    battery_soc_final          double precision,
    grid_import_mwh            double precision,
    grid_export_mwh           double precision,
    grid_net_cost_eur          double precision,
    grid_import_emissions_tco2 double precision,
    renew_wind_mwh             double precision,
    renew_solar_mwh           double precision,
    load_mwh                   double precision,
    CONSTRAINT dispatch_solution_key UNIQUE (day, method)
);

COMMENT ON TABLE  dispatch_solution                            IS '选定调度方案表：NSGA-III 帕累托前沿经 TOPSIS 选出的单日方案——所选目标值、TOPSIS 权重、以及各设备能量分解；配套的 96 步功率曲线见 dispatch_schedule。';
COMMENT ON COLUMN dispatch_solution.id                         IS '方案主键（自增），dispatch_schedule 通过它引用本方案。';
COMMENT ON COLUMN dispatch_solution.day                        IS '调度日。';
COMMENT ON COLUMN dispatch_solution.method                     IS '生成方法（此处为 nsga3）。';
COMMENT ON COLUMN dispatch_solution.forecast_source            IS '所用预测来源（此处为 lstm）。';
COMMENT ON COLUMN dispatch_solution.n_pareto                   IS '帕累托前沿解的数量。';
COMMENT ON COLUMN dispatch_solution.obj_cost_eur               IS '所选方案的成本目标值（欧元）。';
COMMENT ON COLUMN dispatch_solution.obj_co2_tco2               IS '所选方案的碳排放目标值（吨 CO2）。';
COMMENT ON COLUMN dispatch_solution.obj_peak_mw                IS '所选方案的并网峰值目标值（MW）。';
COMMENT ON COLUMN dispatch_solution.w_cost                     IS 'TOPSIS 成本权重。';
COMMENT ON COLUMN dispatch_solution.w_co2                      IS 'TOPSIS 碳排放权重。';
COMMENT ON COLUMN dispatch_solution.w_peak                     IS 'TOPSIS 峰值权重。';
COMMENT ON COLUMN dispatch_solution.gas_energy_mwh             IS '燃气轮机发电量（MWh）。';
COMMENT ON COLUMN dispatch_solution.gas_fuel_cost_eur          IS '燃气燃料成本（欧元）。';
COMMENT ON COLUMN dispatch_solution.gas_emissions_tco2         IS '燃气轮机碳排放（吨 CO2）。';
COMMENT ON COLUMN dispatch_solution.gas_load_factor            IS '燃气轮机平均负载率。';
COMMENT ON COLUMN dispatch_solution.battery_throughput_mwh     IS '储能吞吐电量（MWh）。';
COMMENT ON COLUMN dispatch_solution.battery_cycles             IS '储能等效循环次数。';
COMMENT ON COLUMN dispatch_solution.battery_degradation_eur    IS '储能退化成本（欧元）。';
COMMENT ON COLUMN dispatch_solution.battery_soc_final          IS '储能末端 SoC。';
COMMENT ON COLUMN dispatch_solution.grid_import_mwh            IS '电网购电量（MWh）。';
COMMENT ON COLUMN dispatch_solution.grid_export_mwh           IS '电网售电量（MWh，本系统无外送时为 0）。';
COMMENT ON COLUMN dispatch_solution.grid_net_cost_eur          IS '电网净购电成本（欧元）。';
COMMENT ON COLUMN dispatch_solution.grid_import_emissions_tco2 IS '购电对应的碳排放（吨 CO2）。';
COMMENT ON COLUMN dispatch_solution.renew_wind_mwh            IS '当日风电可用电量（MWh）。';
COMMENT ON COLUMN dispatch_solution.renew_solar_mwh          IS '当日光伏可用电量（MWh）。';
COMMENT ON COLUMN dispatch_solution.load_mwh                   IS '当日负荷电量（MWh）。';
